### ISSUE TITLE
npm version problem

### ISSUE THREAD

**Issue by dumplingsMing** [arthurkiller/electronic-QQ#7]
The version in package.json of electronic-QQ is 0.1, which cause a invalid version warn while running npm install and an error while running npm start.

**Comment by Desgard** [comment]
I encountered the same problem. /(ㄒoㄒ)/~~

**Comment by arthurkiller** [comment]
@dumplingsMing  @Desgard  sorry for that, dude. But I really toooo busy these days and get stuck on AngularJS. I am a back-end progremar with C/C++/Go and never write any JS before....LOL

We scheduled this issue TODO when I finished the Angular...

This project is because I used to work on Linux and the author of electronic-WeChat said he will never write a wechat in nodejs because he just don't use QQ !!!.So I with my friend wanna to do this based on the electronic-wechat code.

If you two have any idea about this just email me , let's do it together!

**Comment by arthurkiller** [comment]
@dumplingsMing  @Desgard  as for the version problem . don't care about it. because it can not work even you get the correct npm version !!!

really sorry for that. I have scheduled this in 2017 TODO list!!!

**Comment by dumplingsMing** [comment]
This issue can be fixed by just change the version in package.json from
```
  "version": "0.1",
```
to
```
  "version": "0.1.0"
```

However still many issues after doing that wwwwwwwwww.

This is a wonderful project since many people including me are facing the same problem while working in Ubuntu. I'm now using Windows Remote Desktop for qq _(:з」∠)_.

Hope we can help you more on this project next year with some pull requests :)

Anyway, Happy New Year.

**Comment by arthurkiller** [comment]
@dumplingsMing thx a lot dude.You too

**Comment by Desgard** [comment]
And I'm a green hand in front-end, too. I'm a iOS dev. and want to try the PC client. I used the electronic wechat, it's so cool. So I have a plan to develop a QQ client for every system environment, and I can learn the Electron in the same time. 😂 
I'll continue pay attention to this repo, and donate the contributions if i can. 
Thx. 👍
